name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [g++]
    steps:
    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
          build-dir: ${{ runner.workspace }}/build
          cc: gcc
          cxx: g++
          build-type: Debug
          parallel: 14

      
