name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler_cxx: [g++, clang, msvc]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with: 
        cmake_args: -D CMAKE_CXX_COMPILER = ${ { matrix.compiler_cxx } }
                    
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler_cxx: [g++, clang, msvc]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with: 
        cmake_args: -D CMAKE_CXX_COMPILER = ${ { matrix.compiler_cxx } }

  macos-build:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler_cxx: [g++, clang, msvc]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install glibc
      run: |
        brew install gawk
        brew install glibc
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with: 
        cmake_args: -D CMAKE_CXX_COMPILER = ${ { matrix.compiler_cxx } }

