name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [g++]
    steps:
    - name: Build
      run: |
        ls
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CC_COMPILER=gcc

