name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      env:
        CXX: ${{ matrix.compiler }}
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
        
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [g++, clang++, msvc]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      env:
        CXX: ${{ matrix.compiler }}
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      

      
