name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [g++]
    steps:
    - name: Build & Test
      run: cmake CmakeLists.txt

      
