name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [msvc]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Vcpkg installation
      run: |
        git clone https://github.com/microsoft/vcpkg 
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg.exe integrate install
    - name: Build project
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -S${{ runner.workspace }}/vcpkg_sample -B${{ runner.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg_sample/vcpkg/scripts/buildsystems/vcpkg.cmake
                    
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Vcpkg installation
      run: |
        git clone https://github.com/microsoft/vcpkg 
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg integrate install
    - name: Build project
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -S${{ runner.workspace }}/vcpkg_sample -B${{ runner.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg_sample/vcpkg/scripts/buildsystems/vcpkg.cmake
               
  macos-build:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Vcpkg installation
      run: |
        git clone https://github.com/microsoft/vcpkg 
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg.exe integrate install
    - name: Build project
      run: |
        export CC=musl-gcc
        cmake -DCMAKE_BUILD_TYPE=Release -S${{ runner.workspace }}/vcpkg_sample -B${{ runner.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg_sample/vcpkg/scripts/buildsystems/vcpkg.cmake
               
