name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler_cxx: [msvc]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cxx: ${{ matrix.compiler_cxx }}
                    
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler_cxx: [g++, clang++]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cxx: ${{ matrix.compiler_cxx }}

  macos-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler_cxx: [g++, clang++]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      run: cmake -DCMAKE_BUILD_TYPE=Release -S${{ runner.workspace }}/vcpkg_sample -B${{ runner.workspace }}/build
